version: "3.8"
services:
    main:
        build: .
        container_name: Archie
        volumes:
            - /home/server/Archie-data:/bot/data
        environment:
            - TOKEN: ${{ secrets.TOKEN }}
